version: '3.7'

services:
  app:
    build:
      context: .
    image: yolobazak/linearb-atm_app
    ports:
      - "8000:8000"
    volumes:
      - ./ATM_api:/ATM_api
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
    depends_on:
      - migration

  migration:
    image: yolobazak/linearb-atm_app
    command: python manage.py migrate --noinput
    volumes:
      - ./ATM_api:/ATM_api



